version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./app/dist:/var/www/html
      - ./volumes/nginx/conf.d/:/etc/nginx/conf.d
      - ./volumes/nginx/logs/nginx:/var/log/nginx
    links:
      - prac

  prac:
    image: iamvirgooo/prac:latest
    container_name: prac
    ports:
      - "8888:8000"
    tty: true